server:
  port: 8080

#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:quiz_db
#    username: root
#    password: root
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quiz_db
    username: root
    password: admin
    driver-class-name: org.postgresql.Driver
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
  dialect: org.hibernate.dialect.PostgreSQLDialect

